function set_IEEE_TSP_default_figure_settings()
Nfigs = 2;
set(0,'DefaultTextFontName','Times',...
'DefaultTextFontSize',26*Nfigs,...
'DefaultAxesFontName','Times',...
'DefaultAxesFontSize',26*Nfigs,...
'DefaultLineLineWidth',2*Nfigs,...
'DefaultLineMarkerSize',7*Nfigs);

end



